<h3>What is a Python library? Why do we use Python libraries?

<h6>Efficiency: Libraries provide pre-written code for common tasks, saving developers time and effort.
    
    
    
    

Functionality: They extend Python's capabilities by offering specialized tools and functions for various tasks such as numerical operations, data manipulation, web development, etc.

    
    
    
    
    
Standardization: Libraries establish standardized solutions for common problems, fostering collaboration and making it easier for developers to understand and contribute to projects.
    
    
    
    

Community Support: Many libraries have active developer communities that provide assistance, contribute improvements, and offer documentation, making it easier to resolve issues and learn how to use the library effectively.

    
    
Domain Specific: Certain libraries are tailored for specific domains like data science, web development, or scientific computing, allowing developers to leverage specialized tools and techniques optimized for their particular field of work.

<h3>2. What is the ^ifference between Numpy array any List?

<h6>Certainly, here's one key difference for each:

1. **Homogeneity**:
   - NumPy arrays are homogeneous, meaning all elements must be of the same data type, while lists can contain elements of different data types.

2. **Performance**:
   - NumPy arrays offer better performance for numerical operations compared to lists, especially for large datasets, due to optimized algorithms and memory efficiency.

3. **Memory Efficiency**:
   - NumPy arrays generally require less memory compared to lists, especially for large datasets, because they store data in a contiguous block of memory.

4. **Indexing**:
   - NumPy arrays support advanced indexing techniques such as boolean indexing, fancy indexing, and slicing with strides, providing more flexibility compared to lists.

5. **Specialized Functions**:
   - NumPy provides specialized functions for array manipulation, linear algebra, Fourier transforms, random number generation, etc., which are not available for lists.

<h3>3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [21]:
import numpy as np
my_list = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
my_array = np.array(my_list)
shape = my_array.shape
size = my_array.size
dimension = my_array.ndim
print("Shape:", shape)
print("Size:", size)
print("Dimension:", dimension)


Shape: (3, 4)
Size: 12
Dimension: 2


<h3>4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [23]:
import numpy as np
my_list = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
my_array = np.array(my_list)
my_array[0]

array([1, 2, 3, 4])

<h3>5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [28]:
import numpy as np
my_list = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
my_array = np.array(my_list)
my_array[2,3]

12

<h3>6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [31]:
import numpy as np
my_list = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
my_array = np.array(my_list)
odd_indexed_elements = my_array[1::2, 1::2]
print(odd_indexed_elements)

[[6 8]]


<h3>7. How can you generate a random 3x3 matrix with values between 0 and 1?


<h6>np.random.rand: Generates random values from a uniform distribution between 0 and 1, with specified array dimensions.

<h3>8. Describe the difference between np.random.rand and np.random.randn?

<h6>np.random.randn: Generates random values from a standard normal distribution (mean=0, standard deviation=1), with specified array dimensions.

<h3>9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [33]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
new_arr = arr[np.newaxis, :]
print(new_arr.shape)
print(new_arr)


(1, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


<h3>10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [34]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

<h3>11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

<h3>Index wise multiplication

In [42]:
A2 =[[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
B2= [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
arr_2=np.array(A2)
arr_3=np.array(B2)
print(arr_2.shape,arr_3.shape)
arr_2*arr_3

(3, 4) (3, 4)


array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

<h3>Matix multiplication

In [51]:
A2 =[[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
B2= [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
result_list= [[0, 0, 0, 0], [0, 0, 0, 0],[0, 0, 0, 0]]
arr_2=np.array(A2)
arr_3=np.array(B2)
result=np.array(result_list)
for i in range(0,len(arr_2)):
    for j in range(0,len(arr_3)):
        result=arr_2[i,j]*arr_3[i,j]
result

121

In [53]:
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
B = [[9, 8, 7],
     [6, 5, 4],
     [3, 2, 1]]
result = [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]
for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]
for row in result:
    print(row)


[30, 24, 18]
[84, 69, 54]
[138, 114, 90]


<h3>Add both the matics

In [54]:
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
B = [[9, 8, 7],
     [6, 5, 4],
     [3, 2, 1]]
result = [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]
for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            result[i][j] += A[i][k] + B[k][j]
for row in result:
    print(row)


[24, 21, 18]
[33, 30, 27]
[42, 39, 36]


<h3>- Subtact matix B from A

In [55]:
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
B = [[9, 8, 7],
     [6, 5, 4],
     [3, 2, 1]]
result = [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]
for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            result[i][j] +=  B[k][j]-A[i][k] 
for row in result:
    print(row)


[12, 9, 6]
[3, 0, -3]
[-6, -9, -12]


<h3>+ Divide Matix B by A

In [56]:
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
B = [[9, 8, 7],
     [6, 5, 4],
     [3, 2, 1]]
result = [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]
for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            result[i][j] +=  B[k][j]/A[i][k] 
for row in result:
    print(row)

[13.0, 11.166666666666666, 9.333333333333334]
[3.95, 3.3333333333333335, 2.7166666666666663]
[2.369047619047619, 1.9900793650793651, 1.6111111111111112]


### 12. Which function in Numpy can be used to swap the byte order of an array?
- The function `np.ndarray.byteswap()` can be used to swap the byte order of an array.

### 13. What is the significance of the np.linalg.inv function?
- `np.linalg.inv` computes the inverse of a square matrix, which is significant in solving systems of linear equations and various mathematical computations.

### 14. What does the np.reshape function do, and how is it used?
- `np.reshape` changes the shape of an array without changing its data. It rearranges the elements to fit the new shape.
- Syntax: `np.reshape(array, new_shape)` is used to reshape an array to the specified `new_shape`.

### 15. What is broadcasting in Numpy?
- Broadcasting is a feature in NumPy that allows arrays with different shapes to be combined together for arithmetic operations.
- It enables operations between arrays of different shapes and sizes by automatically aligning dimensions.
